## Exploring Dask Dashboard UI

In [1]:
from dask.distributed import Client
import dask.dataframe as df

client = Client(processes=False, threads_per_worker=2,
                n_workers=3, memory_limit='4GB')
client

### Data Taken from : https://www.kaggle.com/city-of-seattle/seattle-library-collection-inventory

In [2]:
dummy_df = df.read_csv('broken_csvs/libary-part-0[0-2]*.csv')

In [3]:
dummy_df

Dask DataFrame Structure:
               Unnamed: 0 BibNum   Title  Author    ISBN PublicationYear Publisher Subjects ItemType ItemCollection FloatingItem ItemLocation ReportDate ItemCount
npartitions=60
                    int64  int64  object  object  object          object    object   object   object         object       object       object     object     int64
                      ...    ...     ...     ...     ...             ...       ...      ...      ...            ...          ...          ...        ...       ...
...                   ...    ...     ...     ...     ...             ...       ...      ...      ...            ...          ...          ...        ...       ...
                      ...    ...     ...     ...     ...             ...       ...      ...      ...            ...          ...          ...        ...       ...
                      ...    ...     ...     ...     ...             ...       ...      ...      ...            ...          ...          ...        ...       ...
Dask Name: from-delayed, 180 tasks

In [4]:
dummy_df.describe().compute()

/home/kashif/.local/lib/python3.7/site-packages/dask/dataframe/core.py:3876: RuntimeWarning: invalid value encountered in sqrt
  df = func(*args, **kwargs)

         Unnamed: 0        BibNum     ItemCount
count  5.827473e+06  5.827473e+06  5.827473e+06
mean   9.713166e+04  2.497652e+06  1.217426e+00
std    5.608814e+04           NaN  2.153572e+00
min    0.000000e+00  4.000000e+00  1.000000e+00
25%    4.872525e+04  2.390729e+06  1.000000e+00
50%    9.745050e+04  2.900894e+06  1.000000e+00
75%    1.965775e+05  3.156114e+06  1.000000e+00
max    1.971360e+05  3.343999e+06  7.920000e+02

In [5]:
dummy_df.head()

,Unnamed: 0,BibNum,Title,Author,ISBN,PublicationYear,Publisher,Subjects,ItemType,ItemCollection,FloatingItem,ItemLocation,ReportDate,ItemCount
0,0,3011076,A tale of two friends / adapted by Ellie O'Rya...,"O'Ryan, Ellie","1481425730, 1481425749, 9781481425735, 9781481...",2014.,"Simon Spotlight,","Musicians Fiction, Bullfighters Fiction, Best ...",jcbk,ncrdr,Floating,qna,2017-09-01T00:00:00.000,1
1,1,2248846,"Naruto. Vol. 1, Uzumaki Naruto / story and art...","Kishimoto, Masashi, 1974-",1569319006,"2003, c1999.","Viz,","Ninja Japan Comic books strips etc, Comic book...",acbk,nycomic,NaN,lcy,2017-09-01T00:00:00.000,1
2,2,3209270,"Peace, love & Wi-Fi : a ZITS treasury / by Jer...","Scott, Jerry, 1955-","144945867X, 9781449458676",2014.,"Andrews McMeel Publishing,",Duncan Jeremy Fictitious character Comic books...,acbk,nycomic,NaN,bea,2017-09-01T00:00:00.000,1
3,3,1907265,The Paris pilgrims : a novel / Clancy Carlile.,"Carlile, Clancy, 1930-",0786706155,c1999.,"Carroll & Graf,","Hemingway Ernest 1899 1961 Fiction, Biographic...",acbk,cafic,NaN,cen,2017-09-01T00:00:00.000,1
4,4,1644616,"Erotic by nature : a celebration of life, of l...",NaN,094020813X,"1991, c1988.","Red Alder Books/Down There Press,","Erotic literature American, American literatur...",acbk,canf,NaN,cen,2017-09-01T00:00:00.000,1

In [6]:
# Currently in 1.2.1 inplace arguement is not supported
dummy_df = dummy_df.drop('Unnamed: 0', axis=1)

In [7]:
dummy_df.head()

,BibNum,Title,Author,ISBN,PublicationYear,Publisher,Subjects,ItemType,ItemCollection,FloatingItem,ItemLocation,ReportDate,ItemCount
0,3011076,A tale of two friends / adapted by Ellie O'Rya...,"O'Ryan, Ellie","1481425730, 1481425749, 9781481425735, 9781481...",2014.,"Simon Spotlight,","Musicians Fiction, Bullfighters Fiction, Best ...",jcbk,ncrdr,Floating,qna,2017-09-01T00:00:00.000,1
1,2248846,"Naruto. Vol. 1, Uzumaki Naruto / story and art...","Kishimoto, Masashi, 1974-",1569319006,"2003, c1999.","Viz,","Ninja Japan Comic books strips etc, Comic book...",acbk,nycomic,NaN,lcy,2017-09-01T00:00:00.000,1
2,3209270,"Peace, love & Wi-Fi : a ZITS treasury / by Jer...","Scott, Jerry, 1955-","144945867X, 9781449458676",2014.,"Andrews McMeel Publishing,",Duncan Jeremy Fictitious character Comic books...,acbk,nycomic,NaN,bea,2017-09-01T00:00:00.000,1
3,1907265,The Paris pilgrims : a novel / Clancy Carlile.,"Carlile, Clancy, 1930-",0786706155,c1999.,"Carroll & Graf,","Hemingway Ernest 1899 1961 Fiction, Biographic...",acbk,cafic,NaN,cen,2017-09-01T00:00:00.000,1
4,1644616,"Erotic by nature : a celebration of life, of l...",NaN,094020813X,"1991, c1988.","Red Alder Books/Down There Press,","Erotic literature American, American literatur...",acbk,canf,NaN,cen,2017-09-01T00:00:00.000,1

In [8]:
group_publication_yr = dummy_df.groupby('PublicationYear').count()

In [9]:
group_publication_yr.compute()

,BibNum,Title,Author,ISBN,Publisher,Subjects,ItemType,ItemCollection,FloatingItem,ItemLocation,ReportDate,ItemCount
PublicationYear,,,,,,,,,,,,
"""1972.",3,3,0,0,3,3,3,3,0,3,3,3
(1945).,6,6,6,0,6,6,6,6,0,6,6,6
(1945?).,6,6,6,0,6,6,6,6,0,6,6,6
(1966),21,21,21,0,21,21,21,21,0,21,21,21
(1967),26,26,26,0,26,19,26,26,0,26,26,26
(1967).,15,15,15,0,15,12,15,15,0,15,15,15
(1971).,9,9,9,3,9,9,9,9,0,9,9,9
(1973).,12,12,12,3,12,9,12,12,0,12,12,12
",c1995.",15,15,15,15,15,15,15,15,0,15,15,15
-1896.,4,4,0,0,4,4,4,4,0,4,4,4
-1906-07.,4,4,4,0,4,4,4,4,0,4,4,4
-1920.,7,7,4,0,7,7,7,7,0,7,7,7
-1921.,4,4,0,0,4,4,4,4,0,4,4,4
-1921],3,3,0,0,3,3,3,3,0,3,3,3
-1941.,5,5,5,0,5,5,5,5,0,5,5,5
-1946.,5,5,5,0,5,5,5,5,0,5,5,5
-1957.,9,9,5,0,6,9,9,9,0,9,9,9
-1958.,4,4,0,0,4,4,4,4,0,4,4,4
-1966.,17,17,9,0,17,17,17,17,0,17,17,17
-1968.,8,8,4,0,8,8,8,8,0,8,8,8
-1969.,9,9,5,0,9,9,9,9,0,9,9,9
-1973.,31,31,0,0,31,31,31,31,0,31,31,31
-1978.,8,8,0,0,8,8,8,8,0,8,8,8
-1981.,9,9,0,0,9,9,9,9,0,9,9,9
-1983.,13,13,5,0,13,13,13,13,0,13,13,13
-1986.,9,9,0,0,9,9,9,9,0,9,9,9
-1987,4,4,0,0,4,4,4,4,0,4,4,4
-1993.,17,17,0,0,17,17,17,17,0,17,17,17
-1994.,17,17,9,0,17,17,17,17,0,17,17,17
-1994],3,3,0,0,3,3,3,3,0,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...
"[between 2000-2009?], c1958.",2,2,2,0,2,2,2,2,0,2,2,2
© 2014.,1,1,1,1,1,1,1,1,0,1,1,1
©2017-,4,4,0,0,4,4,4,4,0,4,4,4
"2001, @1999.",1,1,1,1,1,1,1,1,0,1,1,1
"2003, ©1973.",3,3,3,3,3,3,3,3,0,3,3,3
"2003, ©1998.",1,1,1,1,1,1,1,1,0,1,1,1
"2007, ©1997.",2,2,2,2,2,2,2,2,0,2,2,2
"2011, ©1946.",1,1,1,1,1,1,1,1,1,1,1,1
"2012, ©2009.",2,2,2,2,2,2,2,2,0,2,2,2
"2017, c2005.",2,2,2,2,2,2,2,2,0,2,2,2
"2017, c2012.",2,2,2,2,2,2,2,2,2,2,2,2
"[1998], c1926.",2,2,2,2,2,2,2,2,0,2,2,2
"[2003], ©1995.",1,1,1,1,1,1,1,1,0,1,1,1
"[2010], ©1996.",2,2,2,2,2,2,2,2,2,2,2,2
"[2011], ℗2010, ©2011.",1,1,1,1,1,1,1,1,1,1,1,1
"[2017], ℗2016.",3,3,3,0,3,3,3,3,2,3,3,3
[©1926],1,1,1,0,1,1,1,1,0,1,1,1
"[©2002], ℗1971.",1,1,1,0,1,1,1,1,0,1,1,1
©1917.,1,1,0,0,1,1,1,1,0,1,1,1
"©1993, ©1970.",2,2,2,0,2,2,2,2,2,2,2,2
©2018.,7,7,7,7,7,7,7,7,0,7,7,7
"℗2017, 2003.",1,1,1,1,1,1,1,1,1,1,1,1
"[198-?], ©1952.",1,1,1,1,1,1,1,1,0,1,1,1
"[2012], ℗1998.",1,1,1,0,1,1,1,1,1,1,1,1
[2016]-,1,1,1,0,1,1,1,1,0,1,1,1
"[2017], ©2002.",2,2,0,2,2,2,2,2,2,2,2,2
©1902.,1,1,1,0,1,1,1,1,0,1,1,1
©1926.,1,1,1,0,1,1,1,1,0,1,1,1
©1995-2016.,1,1,0,0,1,1,1,1,0,1,1,1
"©2009, ©2006.",1,1,0,0,1,1,1,1,0,1,1,1

In [10]:
group_author = dummy_df.groupby('Author')['ItemCount'].sum()

In [11]:
group_author.compute()

Author
!!! (Musical group)                                                 85
"Avion,", pseud.                                                     8
'N Sync (Musical group)                                              8
(Alina Iosifovna)                                                    9
-Ky                                                                  5
.38 Special (Musical group)                                          5
10,000 Maniacs (Musical group)                                      60
2 Chainz, 1977-                                                     66
3 Doors Down (Musical group)                                        35
311 (Musical group)                                                 58
3OH!3 (Musical group)                                               27
5 Browns                                                            23
5 Seconds of Summer (Musical group)                                 45
50 Cent (Musician)                                                 222
7 Year Bitch (Musical group)                                        16
@DOGSOFINSTAGRAM.                                                   28
A Camp (Musical group)                                               3
A$AP Ferg, 1988-                                                    36
A$AP Rocky (Rapper), 1988-                                          30
A-Wa (Musical group)                                                20
A-ha (Musical group)                                                71
A.B. Dick Company                                                   23
AAS Goddard Memorial Symposium (12th : 1974 : Washington, D. C)      8
AASHTO Value Engineering Conference (1987 : Seattle, Wash.)          4
AC/DC (Musical group)                                              186
AFI (Musical group)                                                 22
ALA.NI.                                                             24
AM (Musician)                                                       14
Aagesen, Colleen.                                                   18
Aalto, Alvar, 1898-1976                                             17
                                                                  ...
Pirulo y La Tribu (Musical group)                                    1
Pisenti, Joseph                                                      4
Reinhardt, Kassandra                                                 2
Reintgen, Scott                                                      2
Richards, Andrea                                                     2
Schofield, George H.                                                 1
Seifert, Marty, 1972-                                                3
Shacter, Phyllis,                                                    1
Shane, Jackie.                                                       2
Shirai, Kaiu.                                                        1
Smith, Andrew O., 1962-                                              1
Snyder, Robert, 1916-2004                                            1
Solfrini, Valentina                                                  1
Sory Sanlé, 1943-                                                    1
Sprinkle, Timothy                                                    3
Søderberg, Marie Tourell,                                            1
Terri, Salli                                                         1
Thomas, Richard F., 1950-                                            4
Tišma, Aleksandar, 1924-2003,                                        2
Torres, Victor, 1943-                                                3
Valentine, S. P. (Stuart P.), 1942-                                  1
Veach, Chad, 1979-                                                   1
Victor, Divya                                                        1
Walker, Ingrid                                                       2
Wall, William, 1955-                                                 1
Weaver, Ellice,                                                      1
Wells, Mason,                                                        1
Wong, G.                                                             1
Harris, Roy, 1898-1979,                                              1
Samuelson-Brown, Randi                                               1
Name: ItemCount, Length: 239603, dtype: int64

In [12]:
len(dummy_df)

5827473

#### Reference : https://stackoverflow.com/a/29581287/8160718

In [14]:
import re
def extract_year(year_text, *args, **kwargs):
    if type(year_text)==type(''):
        return re.findall("[-+]?[\d]+(?:,\d\d\d)*[\.]?\d*(?:[eE][-+]?\d+)?", year_text)
    else:
        return year_text

seperate_publication_year = dummy_df['PublicationYear'].apply(extract_year,
                                                           axis=1,
                                                           meta=('PublicationYear', 'object'))

In [15]:
seperate_publication_year.compute()

0             [2014.]
1       [2003, 1999.]
2             [2014.]
3             [1999.]
4       [1991, 1988.]
5             [1997.]
6             [1989.]
7              [2017]
8             [2017.]
9              [2017]
10            [2014.]
11             [2015]
12             [2006]
13            [2017.]
14            [2017.]
15            [2015.]
16            [2016.]
17             [2015]
18            [2016.]
19            [2008.]
20            [2016.]
21            [2000.]
22            [1960.]
23            [2000.]
24            [2014.]
25             [2014]
26             [2014]
27            [2005.]
28            [2008.]
29            [2004.]
            ...
2211           [2016]
2212           [2014]
2213           [1986]
2214           [2013]
2215           [2013]
2216          [2016.]
2217           [2017]
2218          [2013.]
2219          [2004.]
2220    [2014, 2000.]
2221           [1999]
2222           [2016]
2223          [2010.]
2224           [1985]
2225           [2002]
2226           [1989]
2227          [1991.]
2228          [2017.]
2229           [2016]
2230           [2015]
2231           [2011]
2232          [1921.]
2233          [2017.]
2234          [2003.]
2235           [2015]
2236          [2014.]
2237           [1971]
2238           [2000]
2239           [1988]
2240           [2015]
Name: PublicationYear, Length: 5827473, dtype: object

In [17]:
dummy_df.nlargest(5, 'ItemCount').compute()

distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 2.87 GB -- Worker memory limit: 4.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 2.87 GB -- Worker memory limit: 4.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 2.89 GB -- Worker memory limit: 4.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 2.89 GB -- Worker memory limit: 4.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 2.89 GB -- Worker memory limit: 4.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 2.89 GB -- Worker memory limit: 4.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 2.90 GB -- Worker memory limit: 4.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 2.90 GB -- Worker memory limit: 4.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 2.90 GB -- Worker memory limit: 4.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 2.97 GB -- Worker memory limit: 4.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 2.83 GB -- Worker memory limit: 4.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 2.83 GB -- Worker memory limit: 4.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 2.91 GB -- Worker memory limit: 4.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 2.94 GB -- Worker memory limit: 4.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 2.96 GB -- Worker memory limit: 4.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 2.93 GB -- Worker memory limit: 4.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 2.93 GB -- Worker memory limit: 4.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 2.93 GB -- Worker memory limit: 4.00 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 2.56 GB -- Worker memory limit: 4.00 GB

,BibNum,Title,Author,ISBN,PublicationYear,Publisher,Subjects,ItemType,ItemCollection,FloatingItem,ItemLocation,ReportDate,ItemCount
127755,871761,Official gazette of the United States Patent a...,NaN,NaN,NaN,"U.S. Dept. of Commerce, Patent and Trademark O...",Patents United States Periodicals,arbk,caref,NaN,cen,2017-09-01T00:00:00.000,792
33650,871761,Official gazette of the United States Patent a...,NaN,NaN,NaN,"U.S. Dept. of Commerce, Patent and Trademark O...",Patents United States Periodicals,arbk,caref,NaN,cen,2017-10-01T00:00:00.000,792
72404,871761,Official gazette of the United States Patent a...,NaN,NaN,NaN,"U.S. Dept. of Commerce, Patent and Trademark O...",Patents United States Periodicals,arbk,caref,NaN,cen,2017-11-01T00:00:00.000,792
101483,871761,Official gazette of the United States Patent a...,NaN,NaN,NaN,"U.S. Dept. of Commerce, Patent and Trademark O...",Patents United States Periodicals,arbk,caref,NaN,cen,2017-12-01T00:00:00.000,792
145777,3068478,Annual book of ASTM standards.,American Society for Testing and Materials,NaN,c1970-c2001.,"ASTM,","Materials Standards United States Periodicals,...",arbk,cs7r,NaN,cen,2017-09-01T00:00:00.000,547

### Reference : https://distributed.readthedocs.io/en/latest/diagnosing-performance.html#